alephjs/aleph.js

- html.ts
- project.ts
> Preload All Scripts

- project.ts
https://github.com/alephjs/aleph.js/issues/12
See https://nextjs.org/docs/advanced-features/src-directory
- If a project contains `/src/pages` then change the `srcDir` to `/src`, otherwise default to `/`
- Need to add either tests or update one of/all of the examples
- Need to update documentation
> feat: enable src directory

- hooks.ts
Just removing an undefined type import (`AlephEnv`) in `hooks.ts`
> fix(hooks): Remove undefined import

- .gitignore
- project.ts
- routing.ts
- server.ts
- launch.json added to .gitignore to be able to attach my own projects for incremental debugging.
- Fixed #31, but only for public file paths.
- added decodeURI().
- moved the code block up to top of the serving order.
- const lastModified = info.mtime?.toUTCString() ?? new Date().toUTCString()
- Deno.lstat -> Deno.lstatSync, Deno.readFile -> Deno.readFileSync
> Fix: Lack of URL encoding processing #31

- plugins/sass.ts
- plugins/sass_test.ts
Currently the SASS plugin only supports SCSS #40, this adds a solution for that.
> SASS Support for SASS Plugin

- hooks.ts
Added the `withUseDeno` HOC to use `useDeno` in class components, as an equivalent of `getStaticProps` of **Next.js**.
Asked in #22.
> feat: add withDeno HOC

- api.ts
- multiparser.ts
- multiparser_test.ts
- std.ts
- types.ts
Hi!
After we talk on the #35, I did created a new parser for this project. I did use as a base structure the parser from [deligenius/multiparser](https://github.com/deligenius/multiparser).
Besides that I did change the try/catch block, know any error should be resolved in the request function instead of the API call, that's what you thought in the #35, right?
Any suggestions to improve this parser?
> feat: created new multiparser

- cli/dev.ts
- cli/start.ts
- server.ts
This allows the user to change the hostname in production mode -
```
Start the app in production mode
Usage:
aleph start <dir> [...options]
<dir> represents the directory of the aleph.js app,
if the <dir> is empty, the current directory will be used.
Options:
--host           The address at which the server is to be started.
-p, --port       A port number to start the aleph.js app, default is 8080
-L, --log-level  Set log level [possible values: debug, info]
-r, --reload     Reload source code cache
-h, --help       Prints help message
```
Usage - 
`aleph start --host <hostname> <project>`
> Implementing --host flag for production.

- cli.ts
- project.ts
- version.ts
This is [the convention of the Deno standard library](https://github.com/denoland/deno/blob/1728b3ba1972faf532f261d2a7cfd6130d0f548f/std/version.ts#L8), so I think it makes sense to do the same thing here.
> Rename version to VERSION

- .github/workflows/aleph_in_deno.yml
- plugins/sass_test.ts
Fix the sass tests so that they pass
> test: remove assignment statement to location

- framework/react/bootstrap.ts
- server/project.ts
use a `<div id="__aleph">` instead of a `main` tag to allow for stuff like `<header>` and `<footer>` while remaining semantically correct.
> refactor: use div instead of main

- cli/build.ts
- cli/dev.ts
- cli/start.ts
- server/app.ts
- server/server.ts
Hi there!Thanks for the amazing job on this. I've been using it and it works great, for such a short time! I also have a few ideas and plan to contribute back.
While browsing through the code I found out that the class exported by server had an apparent typo, it was `Appliaction` instead of `Application`.
This PR fixes it. Since it's an exported file in `server`, I don't know if anyone's using it by directly importing the file, but since it isn't exported in `mod.ts`, it should be fine.
**Note**: Another thing I noticed is that this repo isn't formatted according to `deno fmt`, should it?
> fix: rename Appliaction to Application

- cli/init.ts
#157 
- Fix vscode setting `deno.impot_map` to `deno.importMap`
> [157]Fix vscode setting on init cli

- compiler/src/fast_refresh.rs
This fixes a bug in the react refresh transformer which caused the original HOC to be assigned to rather than the handle. This manifested as errors at runtime due to assignment to a const variable.
> Fix order of assignments in react refresh hocs

- framework/react/hooks.ts
This makes useDeno always refresh on each request.
It was also possible to pass a small value, e.g., `0.0000001`, but this is less hackish.
> Allow setting revalidate to 0

- server/app.ts
The specified `outputDir` does not work partially.
```
$ deno install --unstable -A -f -n aleph https://deno.land/x/aleph/cli.ts
$ aleph --version
aleph.js 0.3.0-alpha.28
deno 1.8.3
v8 9.0.257.3
typescript 4.2.2
$ aleph init hello
$ cd hello
$ echo '
import type { Config } from "https://deno.land/x/aleph@v0.3.0-alpha.28/types.ts"
export default (): Config => ({
outputDir: "/docs"  
})
' > aleph.config.ts
$ aleph build
$ ls dist
_aleph  logo.svg
$ ls docs
404.html  _aleph  index.html
```
I expect the following:
```
$ ls dist
ls: cannot access 'dist': No such file or directory
$ ls docs
404.html  _aleph  index.html  logo.svg
```
I fixed it.
I would appreciate it if you could check it.
> fix for outputDir

- server/api.ts
- types.ts
`redirect` replies to redirect the client to another URL with optional response `status` defaulting to 302.
> feat(server): `redirect` replies to redirect the client to another URL

- CONTRIBUTING.md
- framework/core/redirect_test.ts
- shared/fs_test.ts
This PR adds unit tests for `redirect.ts`. In order to get the first line of the `redirect.redirect` function to run under test, the `--location` flag needs to be set on the command line.
Deno restricts setting `location.href` in a non-browser environment, so I could not test the 2nd `if` conditional in the `redirect` function. Also, since there is no way to mock out a dependency in Deno at this point, the `events.emit()` call could not be verified in a test.
> test: Add tests for redirect.ts

- CONTRIBUTING.md
Add rules over how our git commit messages this leads to more readable messages that are easy to follow when looking through the project history.
> docs: Add Commit message guidelines

- examples/anchor-links/app.tsx
- examples/anchor-links/pages/about.tsx
- examples/anchor-links/pages/colors/[name].tsx
- examples/anchor-links/pages/index.tsx
- examples/anchor-links/pages/query.tsx
- framework/react/components/Anchor.ts
Taken from next.js:
https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L89
Also hijacks the `hello-world-src-dir` example for testing navigation behavior.  This example demonstrates bugs #230 (and maybe also #217) if you:
* Click `About Blank` to open in new tab
* Switch to new tab and hover over `Back home`
* index.css stylesheet gets loaded and page appearance changes.
Anyway it would be nice to have an example either in this repo or separate repo that exercises all the navigation + data loading features for testing purposes.
> Anchor tag respects modifiers

- framework/core/events.ts
- framework/core/events_test.ts
Adds `test_vents.ts` from Deno repo and modified `events.ts` -- that was originally copied over from the Deno repo --  with new validation code in `setMaxListeners()`.
> Added tests for framework/core/events copied from Deno repo

- plugins/markdown.ts
I thought the condition of `className` in `markdown.ts` was not correct, so I fixed it.
> Fix the condition of meta.className

- framework/react/helper.ts
Currently, only react components with fully uppercase names are detected as react components.
Unless I'm misunderstanding something fundamentally about how react/aleph.js work, then it should also match any names with both uppercase and lowercase letters.
> react: fix detection of react components

- examples/anchor-links/app.tsx
- examples/css-modules/app.tsx
- examples/hello-world-spa/app.tsx
- examples/hello-world/app.tsx
- examples/markdown-pages/app.tsx
- examples/windicss/app.tsx
- examples/with-src-dir/src/app.tsx
- types.d.ts
Related: #379 
with this PR you can now easily add app props to your `app.tsx` page like this:
```ts
import React from 'react'
import { AppProps } from 'aleph/types.d.ts'
export default function App({ Page, pageProps }: AppProps) {
return (
<main>
<head>
<meta name="viewport" content="width=device-width" />
</head>
<Page {...pageProps} />
</main>
)
}
```
> feat: add `AppProps`

- examples/hello-world-ssr/app.tsx
- examples/hello-world-ssr/pages/index.tsx
- framework/react/bootstrap.ts
The `ssr-data` in HTML is not passed to props, because 
* `createPageRoute` sets `ssrData` (in `pagedata://`) to page component props
* `loadSSRDataFromTag` sets `ssr-data` from HTML into memory (`pagedata://`)
* `createPageRoute` is called before `loadSSRDataFromTag` is called.
- page component gets empty props
so,  I moved `loadSSRDataFromTag` before `createPageRoute`.
`examples/hello-world-ssr` is same as [SSR sample in the document](https://alephjs.org/docs/basic-features/ssr-and-ssg).
1. run the sample
2. check the `serverTime` in HTML is passed to UI
> Fix SSR data passing

- commands/analyze.ts
It seems that `commands/analyze.ts` contains code that will never be executed, so this PR removes it.
> Remove deadcode from `commands/analyze.ts`

- .github/workflows/testing.yml
It seems that [denolib/setup-deno](https://github.com/denolib/setup-deno) has already been archived. This PR migrates it to [the official setup-deno action](https://github.com/denoland/setup-deno).
> Migrate from denolib/setup-deno to denoland/setup-deno

- server/aleph.ts
The callback is awaited in `createSPAIndexHtml()` but not in `#renderPage()`
> Await renderListener callback

- server/aleph.ts
I changed my code according to the "[I18N routing](https://alephjs.org/docs/basic-features/routing#i18n-routing)" in the official documentation, but it did not work correctly.
```
$ deno --version
deno 1.14.0 (release, x86_64-apple-darwin)
v8 9.4.146.15
typescript 4.4.2
$ aleph --version
aleph.js 0.3.0-beta.14
deno 1.14.0
v8 9.4.146.15
typescript 4.4.2
```
Maybe this bug is caused by a change made in [16483f9](https://github.com/alephjs/aleph.js/commit/16483f96a2020c829b951185a624645d33eb49eb#diff-8033e9b81c9757b4f6b0dffdbd5f34f7fbc5a59761f876c863768a9da20ea1b7). In this commit, [this code](https://github.com/alephjs/aleph.js/blob/16483f96a2020c829b951185a624645d33eb49eb/server/aleph.ts#L145-L146) also needed to be changed.
Check the problem by using `v0.3.0-beta.14` and making the …
> Fix i18n routing

- server/aleph.ts
Regardless of the `i18n.locales` option in aleph.config.ts, all language generation results using SSG use `defaultLocale` for the `lang` attribute of \<html\> tag. The cause of this problem is that the URL received by the `_createRouter` function does not have a `/` at the beginning, which does not work as expected. ([framework/core/routing.ts#L139-L146](https://github.com/alephjs/aleph.js/blob/55d80d13df7b17a71df946dd8c322d1ae4cc59a8/framework/core/routing.ts#L139-L146))
```ts
// examples/hello-world-i18n/aleph.config.ts
import type { Config } from 'aleph/types'
export default (): Config => ({
ssr: true, // This problem only occurs when the `ssr` option is `true`.
i18n: {
defaultLocale: 'en',
locales: ['en', 'zh']
}
})
```
```
$ ALEPH_DEV=true deno run -A --unstable …
```
> Fix the `lang` attribute of the <html> tag generated by SSG

- examples/hello-world-ssr/pages/index.tsx
- types.d.ts
This change is a proposal to add a generic type parameter to the `SSROptions` type that,
as a result, provides a type for the returned props object. This models
after React's type generics for component types.
See `examples/hello-world-ssr/pages/index.tsx` for usage example.
> Proposal: Add Props generic type to SSROptions

- bundler/mod.ts
Improve the error message when a `<script>` tag fails to load.
See https://github.com/getsentry/sentry-javascript/issues/2546#issuecomment-703331367
> More useful Error in import onerror

- README.md
The code is mistakenly labeled as `ts` while it should be `tsx`.
> Fix example code highlighting in README

- cli.ts
Ctrl-C is propagated to child processes when you invoke the cli from your terminal, but if you start aleph in testing, then SIGINT (Ctrl-C) is not sent to child process. That causes the child process remaining after test runs.
This PR fixes the above issue.
[This node.js issue](https://github.com/nodejs/node/issues/13538) discusses a similar problem. See especially [this comment](https://github.com/nodejs/node/issues/13538#issuecomment-307799666)
> fix: propagate SIGINT to child process

- server/mod.ts
navigator.userAgent has become getter-only property at https://github.com/denoland/deno/pull/14415, and we can't set it anymore. This PR avoids error with that
> fix: avoid setting userAgent when it's already set

- commands/dev.ts
specifier does not match, hmr is not available on windows
> fix: Relative returns \ on Windows OS

- init.ts
Howdy! My first contribution to Aleph.js here is quite minimal, just a typo fix.
Thanks for the amazing project!
> fix: typo in init.ts
